# This workflow will build a Swift project and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Swift 6.1
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.1"
        
    - name: Build
      run: swift build -v
      
    - name: Run Tests
      run: swift test -v
