# This workflow will run tests

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Swift 6.1
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.1"
      
    - name: Select Xcode 16
      run: |
        sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
        xcodebuild -version
        
    - name: Run Tests
      run: xcodebuild test -scheme TCANestedItemsPicker -skipMacroValidation -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0'
